name: Terraform Plan and Apply On Merge
 
on:
  workflow_dispatch:
  # # Trigger when a pull request is created or updated
  # pull_request:
  #   types:
  #     - opened
  #     - synchronize
 
  # # Trigger when a merge happens to the main branch, NOTE: should be a merge.  No direct push to main should be allowed
  # push:
  #   branches:
  #     - main
 
jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
 
    permissions:
      id-token: write
      contents: read
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: us-west-2
          role-duration-seconds: 900
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}
 
      - name: Terraform Init
        working-directory: roots/prefix_lists
        run: terraform init
 
      - name: Setup the value for our SourceControl tag
        id: setup_source_control_tag
        run: |
          SOURCE_CONTROL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}
          echo "Source Control Value: $SOURCE_CONTROL"
          echo "SOURCE_CONTROL=$SOURCE_CONTROL" >> $GITHUB_ENV
 
      # Copy the existing .tfvars file from the env/ directory
      - name: Copy .tfvars file
        working-directory: roots/prefix_lists
        run: |
          cp env/5017.tfvars dynamic.auto.tfvars
 
      # Append dynamic variables to the copied .tfvars file
      - name: Append dynamic variables to .tfvars file
        working-directory: roots/prefix_lists
        run: |
          echo 'management_account_id = "261444051627"' >> dynamic.auto.tfvars
          echo 'SourceControl = "${{ env.SOURCE_CONTROL }}"' >> dynamic.auto.tfvars
 
      - name: Show .tfvars file
        working-directory: roots/prefix_lists
        run: |
          cat dynamic.auto.tfvars
 
      - name: Terraform Plan
        if: github.ref != 'refs/heads/main'
        working-directory: roots/prefix_lists
        run: |
          terraform plan
 
      - name: Terraform Apply if Merge to Main
        if: github.ref == 'refs/heads/main'
        working-directory: roots/prefix_lists
        run: |
          TF_LOG=DEBUG terraform apply -auto-approve