name: Prepare to Import

on:
  workflow_dispatch: 

jobs:
  prepare_to_import:
    runs-on: ubuntu-latest
    # Run only if not on main branch
    if: github.ref != 'refs/heads/main'  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Placeholder
        run: |
          echo "I am a Placeholder"
